# Format with prettier. This will read the `.prettierrc` config file. Any paths specified by `.prettierignore` will be ignored
# Run with npx, see https://prettier.io/docs/en/cli
format:
	npx prettier . --write

start:
	npm start
